%\VignetteIndexEntry{An Introduction to the BPR method}
%\VignetteKeywords{BPR, methylation, gene expression}
%\VignettePackage{BPRMeth}
%\VignetteEngine{knitr::knitr}

\documentclass{article}

<<style-knitr, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@

\bioctitle[BPRMeth: Methylation features for clustering and prediction]{BPRMeth: Higher order methylation features for clustering and prediction in epigenomics studies}
\author{Chantriolnt-Andreas Kapourani\footnote{C.A.Kapourani@ed.ac.uk}}
\date{Modified: 29 July, 2016. Compiled: \today}


\begin{document}

\maketitle

\tableofcontents

\section{Introduction}
DNA methylation is an intensely studied epigenetic mark, yet its functional role is incompletely understood. Attempts to quantitatively associate average DNA methylation to gene expression yield poor correlations outside of the well-understood methylation-switch at CpG islands.

Here we use probabilistic machine learning to extract higher order features associated with the methylation profile across a defined region. These features quantitate precisely notions of shape of a methylation profile, capturing spatial correlations in DNA methylation across genomic regions.  Using these higher order features across promoter-proximal regions, we are able to construct a powerful machine learning predictor of gene expression, significantly improving upon the predictive power of average DNA methylation levels.

\section{Background}
DNA methylation data produced by High Throughput Sequencing (HTS) technology can be modelled with a Binomial distribution:
\begin{equation}
  m \sim \mathcal{B}inom(t, p)
\end{equation}

In practical studies we are interested in learning the methylation patterns of genomic regions which can be represented by an observation vector $\mathbf{y}$. Let $f(x) = \Phi \big(g(x)\big)$ be a latent function representing the methylation profiles and $g(x)$ be of the form:
\begin{equation}
	 g(x) = \sum\limits_{j=0}^{M-1} w_{j} h_{j}(x)
\end{equation}
where $h_{j}(\cdot)$ can be any basis function, e.g. Radial Basis Function (RBF).

Given $f(x)$ the observations $y_{l}$ for each CpG site are i.i.d. Binomial variables, so we can define the joint log-likelihood in factorised form:
\begin{equation} \label{eq:bpr-likelihood}
 \log p(\mathbf{y} | f) = \sum\limits_{l = 1}^{L} \log \bigg( \mathcal{B}inom\big(m_{l} | t_{l}, \Phi(g(x_{l}))\big) \bigg)
\end{equation}
We refer to this observation model as the Binomial Probit Regression (BPR) likelihood function. \emph{Figure 1} shows the process of learning the methylation profile for a specific promoter region using the BPR model. For a more detailed explanation of the statistical method, see \cite{Kapourani2016}.

\begin{figure}[!ht]
\centerline{\includegraphics[width=0.70\textwidth]{model-bpr}}
\caption{\small{Illustration of the process for learning methylation profiles using the BPR model. The inputs to the model are the observed methylation levels of the CpGs across the promoter region, plus the number, with their corresponding centres, of the Radial Basis Functions (RBFs), which in this example are chosen to be four. Using this information the BPR model will learn the optimal coefficients for each RBF using maximum likelihood. Finally, we obtain the underlying methylation profile by a linear combination of the fitted RBFs. One should note that the higher the number of RBFs the better the resolution for the methylation profile.}}
\label{fig:model-performance}
\end{figure}

\section{Analysis Pipeline}
\subsection{Sample Data}
In this vignette, as sample data we will use real datasets that are publicly available from the ENCODE project consortium \cite{Dunham2012}. More specifically we will use the K562 immortalized cell line, with GEO: GSE27584 for the RRBS data and GEO: GSE33480 for the RNA-Seq data. We use the preprocessed files, however, we should note that we have converted the RNA-Seq data from \verb|.gtf| to \verb|.bed| format using the \verb|bedops| tool (\href{http://bedops.readthedocs.io} {http://bedops.readthedocs.io}). We keep only the protein coding genes, and for the purposed of this vignette we focus only on \verb|chr12| and \verb|chr13|. Full details of where to download the data and how to preprocess them are included in the Supplementary Material of \cite{Kapourani2016}.

\subsection{Import and read HTS files}
In the \verb|BPRMeth| package we provide methods for reading files generated from HTS experiments with specific formats. Here, we focus on the ENCODE data described above; hence, we will use the wrapper function \Rfunction{process\_haib\_caltech\_wrap} to obtain the final objects for downstream analysis. The user can implement his own methods for different HTS formats and then use the pipeline described in Figure 2 for obtaining the required objects. First, we load the package:
<<eval=TRUE, echo=TRUE, message=FALSE, results="asis">>=
library(BPRMeth)
@
and obtain the paths for the RRBS and RNA-Seq files with the following commands:
<<eval=TRUE, echo=TRUE, results="asis">>=
rrbs_file <- system.file("extdata", "rrbs.bed", package = "BPRMeth")
rnaseq_file <- system.file("extdata", "rnaseq.bed", package = "BPRMeth")
@

Then, we process both files to obtain the final object which will be used for downstream analysis.  We call the \Rfunction{process\_haib\_caltech\_wrap} function using the default values:
<<eval=TRUE, echo=TRUE, message=FALSE, results="asis">>=
HTS_data <- process_haib_caltech_wrap(rrbs_file, rnaseq_file)
@

Among other information, the \verb|HTS_data| object contains the following data that we need for our analysis. First, the promoter methylation data, where only one region is shown below:
<<eval=TRUE, echo=TRUE>>=
head(HTS_data$methyl_region, 1)
@

Each methylation promoter region is an $L_{i} \times 3$ dimensional matrix, where $L_{i}$ denotes the number of CpGs found in region $i$. The columns contain the following information:
\begin{itemize}
\item{ 1st column: Contains locations of CpGs relative to TSS. Note that the actual locations are scaled to the (-1, 1) region. }
\item{ 2nd column: Contains the total reads of each CpG in the corresponding location.}
\item{ 3rd column: Contains the methylated reads each CpG in the corresponding location.}
\end{itemize}

Second, the corresponding log2 transformed gene expression levels for each promoter region, which can be obtained as follows:
<<eval=TRUE, echo=TRUE>>=
head(HTS_data$gex, 10)
@

Finally, the RNA-Seq data containing annotation data are stored in a \Biocpkg{GRanges} object:
<<eval=TRUE, echo=TRUE>>=
HTS_data$rna_data
@

\bibliography{BPRMeth_vignette}

\end{document}
