# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname model_log_likelihood
#'
#' @export
bpr_log_likelihood <- function(w, X, H, lambda, is_nll) {
    .Call('_BPRMeth_bpr_log_likelihood', PACKAGE = 'BPRMeth', w, X, H, lambda, is_nll)
}

#' @rdname model_log_likelihood
#'
#' @export
bpr_gradient <- function(w, X, H, lambda, is_nll) {
    .Call('_BPRMeth_bpr_gradient', PACKAGE = 'BPRMeth', w, X, H, lambda, is_nll)
}

#' @rdname model_log_likelihood
#'
#' @export
betareg_log_likelihood <- function(w, X, H, lambda, is_nll) {
    .Call('_BPRMeth_betareg_log_likelihood', PACKAGE = 'BPRMeth', w, X, H, lambda, is_nll)
}

#' @rdname model_log_likelihood
#'
#' @export
betareg_gradient <- function(w, X, H, lambda, is_nll) {
    .Call('_BPRMeth_betareg_gradient', PACKAGE = 'BPRMeth', w, X, H, lambda, is_nll)
}

#' @rdname model_log_likelihood
#'
#' @export
sum_weighted_bpr_lik <- function(w, X_list, H_list, r_nk, lambda, is_nll) {
    .Call('_BPRMeth_sum_weighted_bpr_lik', PACKAGE = 'BPRMeth', w, X_list, H_list, r_nk, lambda, is_nll)
}

#' @rdname model_log_likelihood
#'
#' @export
sum_weighted_bpr_grad <- function(w, X_list, H_list, r_nk, lambda, is_nll) {
    .Call('_BPRMeth_sum_weighted_bpr_grad', PACKAGE = 'BPRMeth', w, X_list, H_list, r_nk, lambda, is_nll)
}

#' @rdname model_log_likelihood
#'
#' @export
sum_weighted_betareg_lik <- function(w, X_list, H_list, r_nk, lambda, is_nll) {
    .Call('_BPRMeth_sum_weighted_betareg_lik', PACKAGE = 'BPRMeth', w, X_list, H_list, r_nk, lambda, is_nll)
}

#' @rdname model_log_likelihood
#'
#' @export
sum_weighted_betareg_grad <- function(w, X_list, H_list, r_nk, lambda, is_nll) {
    .Call('_BPRMeth_sum_weighted_betareg_grad', PACKAGE = 'BPRMeth', w, X_list, H_list, r_nk, lambda, is_nll)
}

